Update data-migration-steps.yml

diff --git a/data-migration-steps.yml b/data-migration-steps.yml
--- a/data-migration-steps.yml
+++ b/data-migration-steps.yml
@@ -52,3 +52,125 @@ using this branch:
     
     via legacy ui, navigate to 'Administration > Migrate Existing Diagnosis Data' and proceed to migrate diagnoses, this will take a long while
         query the encounter_diagnosis table to ensure completion by getting a consistent result for 1 minute using this query - `select count(*) from encounter_diagnosis;`
+
+- 18 run following query to generate csv file that maps file on the file system to the corresponding obs:
+    docker exec -it ozone-hsc-mysql-1 rm /tmp/migration_file_paths.csv # if exists
+
+    docker exec -it ozone-hsc-mysql-1 mysql -uroot -p3cY8Kve4lGey openmrs -e "SELECT 'file_path', 'new_file_path'
+    UNION ALL
+    SELECT
+        o.value_text AS file_path,
+        CONCAT(
+            REPLACE(SUBSTRING_INDEX(o.value_text, '/', 1), '/', '-'), 
+            '-',
+            REPLACE(REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(o.value_text, '/', -1), '.', 1), ' ', '-'), '/', '-'),
+            '_', o.uuid,
+            '.', SUBSTRING_INDEX(o.value_text, '.', -1)
+        ) AS new_file_path
+    FROM obs o
+    JOIN concept c ON o.concept_id = c.concept_id
+    WHERE c.uuid LIKE '81f330b5-3f10-11e4-adec-0800271c1b75'
+    AND o.value_text IS NOT NULL
+    INTO OUTFILE '/tmp/migration_file_paths.csv'
+    FIELDS TERMINATED BY ',' 
+    LINES TERMINATED BY '\n';"
+
+
+    docker cp ozone-hsc-mysql-1:/tmp/migration_file_paths.csv migration_file_paths.csv
+
+- 19 Run following bash script as follows:
+    touch complex_obs_migration_script.sh
+
+    nano complex_obs_migration_script.sh
+
+    ##########################
+    ##### Copy over the following script and save:
+
+    #!/bin/bash
+
+    # Get the directory where the script is located
+    script_dir="$(dirname "$(realpath "$0")")"
+
+    # Set the CSV file name (ensure this file exists and is in the same directory as the script)
+    csv_file="$script_dir/migration_file_paths.csv"
+
+    # Check if the CSV file exists
+    if [[ ! -f "$csv_file" ]]; then
+        echo "CSV file not found!"
+        exit 1
+    fi
+
+    # Read the CSV file line by line
+    while IFS=',' read -r file_path new_file_path; do
+        # Skip the header row
+        if [[ "$file_path" == "file_path" ]]; then
+            continue
+        fi
+
+        # Make file paths relative to the script's directory
+        abs_file_path="$script_dir/$file_path"
+        abs_new_file_path="/home/ubuntu/complex_obs/$new_file_path"
+
+        # Check if the source file exists
+        if [[ ! -f "$abs_file_path" ]]; then
+            echo "File not found: $abs_file_path"
+            continue
+        fi
+
+        # Create the target directory if it does not exist
+        target_dir=$(dirname "$abs_new_file_path")
+        if [[ ! -d "$target_dir" ]]; then
+            echo "Target directory does not exist, creating: $target_dir"
+            mkdir -p "$target_dir"
+        fi
+
+        # Move the file
+        mv "$abs_file_path" "$abs_new_file_path"
+        if [[ $? -eq 0 ]]; then
+            echo "Moved: $abs_file_path to $abs_new_file_path"
+        else
+            echo "Failed to move: $abs_file_path"
+        fi
+    done < "$csv_file"
+
+    echo "File move process completed."
+
+    # save script and run it from the root directory containing the un migrated files
+
+    chmod +x complex_obs_migration_script.sh
+
+    ./complex_obs_migration_script.sh
+
+- 21 copy copy the moved files/documents into the complex obs directory inside the OpenMRS container:
+    docker cp /home/ubuntu/complex_obs/. oz-hsc-403-openmrs-1:/openmrs/data/complex_obs/
+
+- 22 run the following database migration turning the migrated obs on the file system into complex obs:
+
+    docker exec -it ozone-hsc-mysql-1 mysql -uroot -p3cY8Kve4lGey openmrs -e "UPDATE obs o
+            JOIN concept c ON o.concept_id = c.concept_id
+            SET
+                o.value_complex = CONCAT(
+                    'm3ks | instructions.default | ', 
+                    CASE 
+                        WHEN SUBSTRING_INDEX(o.value_text, '.', -1) IN ('jpeg', 'png') 
+                             THEN CONCAT('image/', SUBSTRING_INDEX(o.value_text, '.', -1))
+                        ELSE CONCAT('application/', SUBSTRING_INDEX(o.value_text, '.', -1))
+                    END,
+                    ' | ',
+                    CONCAT(
+                        REPLACE(SUBSTRING_INDEX(o.value_text, '/', 1), '/', '-'), 
+                        '-',
+                        REPLACE(REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(o.value_text, '/', -1), '.', 1), ' ', '-'), '/', '-'),
+                        '_', o.uuid,
+                        '.', SUBSTRING_INDEX(o.value_text, '.', -1)
+                    )
+                ),
+                o.concept_id = (SELECT concept_id FROM concept WHERE uuid = 
+                    CASE 
+                        WHEN SUBSTRING_INDEX(o.value_text, '.', -1) IN ('jpeg', 'png') 
+                            THEN '7cac8397-53cd-4f00-a6fe-028e8d743f8e'
+                        ELSE '42ed45fd-f3f6-44b6-bfc2-8bde1bb41e00'
+                    END LIMIT 1),
+                o.value_text = NULL
+            WHERE c.uuid LIKE '81f330b5-3f10-11e4-adec-0800271c1b75'
+            AND o.value_text IS NOT NULL;"
